#!/bin/sh

set -e

# Pull existing container
sudo docker pull ${distribution}:${version}

# Customize container
sudo docker build \
  --rm=true \
  --file=tests/Dockerfile.${distribution}-${version} \
  --tag=${distribution}-${version}:ansible tests

# Run container in detached state
id_file=$(mktemp)
sudo docker run \
  --detach \
  --volume="${PWD}":/etc/ansible/roles/role_under_test:ro \
  ${distribution}-${version}:ansible ${init} > "${id_file}"
container_id="$(cat $id_file)"
echo "Container ID:" "${container_id}"

# Install dependencies.
sudo docker exec "${container_id}" \
  ansible-galaxy install \
    -r /etc/ansible/roles/role_under_test/tests/requirements.yml

# Ansible syntax check.
sudo docker exec "${container_id}" \
  env TERM=xterm \
  ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml \
    --syntax-check

# Ansible lint check.
sudo docker exec "${container_id}" \
  env TERM=xterm \
  ansible-lint /etc/ansible/roles/role_under_test/tests/test.yml \
    --exclude /etc/ansible/roles/geerlingguy.apache \
    --exclude /etc/ansible/roles/geerlingguy.php \
    --exclude /etc/ansible/roles/pcextreme.mariadb

# Check that role installs successfully.
sudo docker exec "${container_id}" \
  env TERM=xterm \
  ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml

# Test role idempotence.
idempotence_file=$(mktemp)
sudo docker exec "${container_id}" \
  env TERM=xterm \
  ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml \
  | tee "${idempotence_file}"
grep -q 'changed=0.*failed=0' "${idempotence_file}" && \
  (echo 'Idempotence test: pass' && exit 0) || \
  (echo 'Idempotence test: fail' && exit 1)

# Check that Clipbucket landing page is up
print_ip_python=$(echo "import sys, json;
print json.load(sys.stdin)[0]['NetworkSettings']['IPAddress']")
container_ip=$(sudo docker inspect "${container_id}" | \
  python -c "${print_ip_python}")
echo "Container IP Address:" "${container_ip}"
curl -s "${container_ip}"  \
  | grep "Login" && \
  (echo 'Landing page test: pass' && exit 0) || \
  (echo 'Landing page test: fail' && exit 1)

# Clean up
sudo docker stop "${container_id}"
sudo docker rm "${container_id}"
