FROM ubuntu:14.04

RUN apt-get update

# Install Ansible
RUN apt-get install -y python-dev libffi-dev python-pip git libssl-dev libxml2-dev libxslt1-dev libjpeg8-dev zlib1g-dev libyaml-dev libpython2.7-dev
RUN pip install ansible ansible-lint paramiko PyYAML Jinja2 httplib2 six

# Install Ansible inventory file
RUN mkdir /etc/ansible
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

