FROM williamyeh/ansible:ubuntu16.04-onbuild

# Install Ansible inventory file
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

# Install ansible-lint
RUN apt-get update
RUN apt-get install -y python-pip
RUN pip install ansible-lint

EXPOSE 80
