FROM ubuntu:14.04

RUN apt-get update

# Install Ansible
RUN apt-get install -y \
  libffi-dev \
  libyaml-dev \
  libpython2.7-dev \
  libssl-dev \
  python-pip \
  python2.7-dev
RUN pip install ansible ansible-lint paramiko PyYAML Jinja2 httplib2 six

# Install Ansible inventory file
RUN mkdir /etc/ansible
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

EXPOSE 80
